version: '3.4'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  urlShortnerApi:
    image: api-service:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-build
    environment: []
    volumes:
      - ./:/app/
    entrypoint: ['npm', 'run', 'start:dev']
    env_file:
      - .env
      # To use DB running on local machine.
    # environment:
    #   - DB_HOST=host.docker.internal
    ports:
      - "4000:4000"
      - "4001:4001"
volumes:
  mongodb:

